export enum Id {
    none = "none",

    user1 = "user1",
    user2 = "user2",

    zeldaBreathOfTheWild = "zeldaBreathOfTheWild",
    marioKart8Deluxe = "marioKart8Deluxe",
    animalCrossingNewHorizons = "animalCrossingNewHorizons",
    humanFallFlat = "humanFallFlat",
    superSmashBrothersUltimate = "superSmashBrothersUltimate",
    gangBeasts = "gangBeasts",
    darkSouls = "darkSouls",
    donkeyKongCountryTropicalFreeze = "donkeyKongCountryTropicalFreeze",
    marioPartySuperstars = "marioPartySuperstars",
    minecraft = "minecraft",
    pikmin3 = "pikmin3",
    pokemonLetsGoPikachu = "pokemonLetsGoPikachu",
    abzu = "abzu",
    borderlands = "borderlands",
    brothers = "brothers",
    celeste = "celeste",
    farmingSimulator20 = "farmingSimulator20",
    hollowKnight = "hollowKnight",
    kirbyAndTheForgottenLand = "kirbyAndTheForgottenLand",
    littleNightmares = "littleNightmares",
    luigisMansion3 = "luigisMansion3",
    newPokemonSnap = "newPokemonSnap",
    pokemonShield = "pokemonShield",
    pokemonShiningPearl = "pokemonShiningPearl",
    superMario3dAllStars = "superMario3dAllStars",
    superMario3dWorld = "superMario3dWorld",
    zeldaLinksAwakening = "zeldaLinksAwakening",
    allAppsButton = "allAppsButton",


    news = "news",
    eShop = "eShop",
    album = "album",
    controller = "controller",
    settings = "settings",
    standby = "standby",
}